<?php
/** @var RicardoMartins_PagBank_Block_Form_Pix $this */
$_code = $this->getMethodCode();
?>
<ul class="form-list ricardomartins-pagbank ricardomartins-pagbank-pix" id="payment_form_<?= $_code ?>" style="display:none;">
    <li class="ricardomartins-pagbank-payment-info-row">
        <div class="payment-info pix-info">
            <p>
                <?= $this->__('Pay safely and instantly!') ?>
                <br>
                <?= $this->__('The QrCode will be displayed at checkout.') ?>
                <br>
                <?= $this->__('You will have %s minutes to pay with your Pix code.', $this->getExpiration()) ?>
            </p>
        </div>
    </li>
    <?php if ($this->isDocumentFieldVisible()): ?>
        <li class="ricardomartins-pagbank-pix-document-row">
            <div>
                <label for="<?= $_code ?>_document" class="required"><?= $this->__('CPF/CNPJ') ?></label>
                <div class="input-box">
                    <input type="text" id="<?= $_code ?>_document" name="payment[data_tax_id]"
                           title="<?= $this->__('CPF/CNPJ') ?>" placeholder="<?= $this->__('CPF/CNPJ') ?>"
                           data-js="document"
                           class="input-text validate-length" />
                </div>
            </div>
        </li>
    <?php endif; ?>
</ul>