<?php
/** @var RicardoMartins_PagBank_Block_Form_Pix $this */
$_code = $this->getMethodCode();
?>
<ul class="form-list ricardomartins-pagbank ricardomartins-pagbank-pix" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="ricardomartins-pagbank-payment-info-row">
        <div class="payment-info pix-info">
            <p>
                <?php echo $this->__('Pay safely and instantly!') ?>
                <br>
                <?php echo $this->__('The QrCode will be displayed at checkout.') ?>
                <br>
                <?php echo $this->__('You will have %s minutes to pay with your Pix code.', $this->getExpiration()) ?>
            </p>
        </div>
    </li>
    <?php if ($this->isDocumentFieldVisible()): ?>
        <li class="ricardomartins-pagbank-pix-document-row">
            <div>
                <label for="<?php echo $_code ?>_document" class="required"><?php echo $this->__('CPF/CNPJ') ?></label>
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_document" name="payment[data_tax_id]" title="<?php echo $this->__('CPF/CNPJ') ?>" class="input-text validate-length" />
                </div>
            </div>
        </li>
    <?php endif; ?>
</ul>
