<?php
/**
 * @var $this RicardoMartins_PagBank_Block_Form_Info_Billet
 */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?> (PagBank - Ricardo Martins)</strong></p>
<?php if($info = $this->getBilletAdditionalData()): ?>
    <div class="code-container">
        <label for="barcode">
            <?php echo $this->__('Barcode:') ?>
        </label>
        <div class="code-content">
            <span>
                <input type="text" id="barcode" class="payment-code" value="<?php echo $this->escapeHtml($info['formatted_barcode']) ?>" readonly="readonly"/>
                <img src="<?php echo $this->getSkinUrl('images/ricardomartins/pagbank/copy-icon.svg'); ?>" alt="<?php echo $this->__('Copy') ?>" title="<?php echo $this->__('Copy') ?>" class="copy-btn"/>
            </span>
            <p class="copied" style="display: none"><?php echo $this->__('Copied ✔') ?></p>
        </div>
    </div>
    <p><b><?php echo $this->__('Your billet expires in %s', $this->escapeHtml($this->formatDateFromString($info['due_date']))) ?></b></p>
    <p>
        <a href="<?php echo $this->escapeUrl($info['payment_link_boleto_pdf']);?>" target="_blank">
            <?php echo $this->__('Download billet file') ?>
        </a>
    </p>
    <p>
        <a href="<?php echo $this->escapeUrl($info['payment_link_boleto_image']);?>" target="_blank">
            <?php echo $this->__('Print billet file') ?>
        </a>
    </p>
<?php endif; ?>