<?php
/**
 * @var $this RicardoMartins_PagBank_Block_Form_Info_Billet
 */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?> (PagBank - Ricardo Martins)</strong></p>
<?php if($info = $this->getBilletAdditionalData()): ?>
    <p>
        <strong>
            <?php echo $this->__('Is Sandbox') ?>:
            <?php echo $this->__($this->escapeHtml($info['is_sandbox'])) ?>
        </strong>
    </p>
    <?php if ($_specificInfo = $this->getSpecificInformation()):?>
        <?php foreach ($_specificInfo as $_label => $_value):?>
            <?php if ($_value === RicardoMartins_PagBank_Model_Method_Cc::CC_PAGBANK_SESSION) continue ?>
            <p>
                <strong><?php echo $this->escapeHtml($_label)?>:</strong>
                <span><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></span>
            </p>
        <?php endforeach ?>
    <?php endif ?>
    <p class="barcode">
        <?php echo $this->__('Barcode:') ?>
        <br>
        <?php echo $this->escapeHtml($info['formatted_barcode']) ?>
    </p>
    <p><b><?php echo $this->__('Billet expiration: %s', $this->escapeHtml($this->formatDateFromString($info['due_date']))) ?></b></p>
    <p>
        <a href="<?php echo $this->escapeUrl($info['payment_link_boleto_pdf']);?>" target="_blank">
            <?php echo $this->__('Download billet file') ?>
        </a>
    </p>
    <p>
        <a href="<?php echo $this->escapeUrl($info['payment_link_boleto_image']);?>" target="_blank">
            <?php echo $this->__('Print billet file') ?>
        </a>
    </p>
<?php endif; ?>
<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <?php if (strpos($_value, RicardoMartins_PagBank_Api_Connect_ConnectInterface::PAGBANK_TRANSACTION_DETAILS_URL) !== false): ?>
            <p>
                <a href="<?php echo $this->escapeUrl($_value);?>" target="_blank">
                    <?php echo $this->escapeHtml($_label) ?>
                </a>
            </p>
            <?php continue; ?>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
