<?php
/**
 * @see RicardoMartins_PagBank_Block_Form_Info_Cc
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<table>
    <tr>
        <td><b><?= $this->__('Is Sandbox') ?>:</b></td>
        <td><b><?= $this->__($this->escapeHtml($this->isSandBox())) ?></b></td>
    </tr>
<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <td><?= $this->escapeHtml($_label)?>:</td>
            <td><?= nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
        </tr>
    <?php endforeach ?>
<?php endif ?>
</table>

<?php echo $this->getChildHtml()?>
