<?php
/**
 * @see RicardoMartins_PagBank_Block_Form_Info_Cc
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<div>
    <?php if ($this->showSecureIcon()): ?>
        <img src="<?php echo $this->getSkinUrl('images/ricardomartins/pagbank/3d-secure.svg') ?>" width="50px" height="61px"
             alt="<?php echo $this->__('3D Secure') ?>" title="<?php echo $this->__('3D Secure') ?>" />
    <?php endif ?>
</div>
<table>
    <tr>
        <td><b><?php echo $this->__('Is Sandbox') ?>:</b></td>
        <td><b><?php echo $this->__($this->escapeHtml($this->isSandBox())) ?></b></td>
    </tr>
<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <?php if (strpos($_value, RicardoMartins_PagBank_Api_Connect_ConnectInterface::PAGBANK_TRANSACTION_DETAILS_URL) !== false): ?>
            <p>
                <a href="<?php echo $this->escapeUrl($_value);?>" target="_blank">
                    <?php echo $this->escapeHtml($_label) ?>
                </a>
            </p>
            <?php continue; ?>
        <?php endif ?>
        <tr>
            <td><?php echo $this->escapeHtml($_label)?>:</td>
            <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
        </tr>
    <?php endforeach ?>
<?php endif ?>
</table>

<?php echo $this->getChildHtml()?>
