<?php
/**
 * @var $this RicardoMartins_PagBank_Block_Form_Info_Pix
 */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?> (PagBank - Ricardo Martins)</strong></p>
<?php if($info = $this->getPixAdditionalData()): ?>
    <p>
        <strong>
            <?php echo $this->__('Is Sandbox') ?>:
            <?php echo $this->__($this->escapeHtml($info['is_sandbox'])) ?>
        </strong>
    </p>
    <div class="pix-qr-container">
        <img src="<?php echo $this->escapeUrl($info['qrcode_image']); ?>" class="pix-qr" alt="PIX QrCode" title="<?php echo $this->__('Scan the code below with your bank\'s app.') ?>" width="200px" />
    </div>
    <p class="qrcode">
        <?php echo $this->__('Pix Code:') ?>
        <br>
        <?php echo $this->escapeHtml($info['qrcode_text']) ?>
    </p>
    <p><b><?php echo $this->__('Pix code expiration: %s', $this->escapeHtml($this->formatDateFromString($info['due_date']))) ?></b></p>
<?php endif; ?>