<?php
/**
 * @var $this RicardoMartins_PagBank_Block_Form_Info_Pix
 */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?> (PagBank - Ricardo Martins)</strong></p>
<?php if($info = $this->getPixAdditionalData()): ?>
    <p>
        <strong>
            <?php echo $this->__('Is Sandbox') ?>:
            <?php echo $this->__($this->escapeHtml($info['is_sandbox'])) ?>
        </strong>
    </p>
    <div class="pix-qr-container">
        <img src="<?php echo $this->escapeUrl($info['qrcode_image']); ?>" class="pix-qr" alt="PIX QrCode" title="<?php echo $this->__('Scan the code below with your bank\'s app.') ?>" width="200px" />
    </div>
    <p class="qrcode">
        <?php echo $this->__('Pix Code:') ?>
        <br>
        <?php echo $this->escapeHtml($info['qrcode_text']) ?>
    </p>
    <p><b><?php echo $this->__('Pix code expiration: %s', $this->escapeHtml($this->formatDateFromString($info['due_date']))) ?></b></p>
<?php endif; ?>
<?php if ($_specificInfo = $this->getSpecificInformation()):?>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <?php if (strpos($_value, RicardoMartins_PagBank_Api_Connect_ConnectInterface::PAGBANK_TRANSACTION_DETAILS_URL) !== false): ?>
            <p>
                <a href="<?php echo $this->escapeUrl($_value);?>" target="_blank">
                    <?php echo $this->escapeHtml($_label) ?>
                </a>
            </p>
            <?php continue; ?>
        <?php endif ?>
        <p>
            <strong><?php echo $this->escapeHtml($_label)?>:</strong>
            <span><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></span>
        </p>
    <?php endforeach ?>
<?php endif ?>
